### ISSUE TITLE
xunit does not work yet with aspnet50 and aspnetcore50?

### ISSUE THREAD

**Issue by StefH** [xunit/aspnet.xunit#11]
When adding these dependencies:
"xunit": "2.0.0-*",
"xunit.runner.aspnet": "2.0.0-*"

I can only compile for .NET 4.5 ? I have the "1.0.0-beta2" version from CLR+CoreCLR installed on my system.

**Comment by bradwilson** [comment]
The support that was shipped with RC1 was pulled, because the ASP.NET team did not publish all the necessary packages. Support will be back with RC2, but for command line runner only (the packages that are missing are the ones used by the Visual Studio runner support).

**Comment by StefH** [comment]
Any information on the release dates for RC2?

**Comment by bradwilson** [comment]
Hoping we'll finish today, which would give us a release on Monday or thereabouts.
