### ISSUE TITLE
NuGet Package Metadata is incorrect

### ISSUE THREAD

**Issue by bradwilson** [xunit/aspnet.xunit#19]

**Comment by bradwilson** [comment]
Still missing the ability to set:

- iconUrl (https://github.com/aspnet/dnx/issues/1460)
- licenseUrl (https://github.com/aspnet/dnx/issues/1461)
- title (https://github.com/aspnet/dnx/issues/1462)

**Comment by davidfowl** [comment]
This should be fixed in the dnvm branch

**Comment by bradwilson** [comment]
Verified.
