### ISSUE TITLE
Task.Factory.StartNew never start the task

### ISSUE THREAD

**Issue by aguacongas** [xunit/aspnet.xunit#20]
Using VS2015 STP6 and beta3 a code starting a task with `Task.Factory.StartNew` doesn't execute the expressiont in parameter while running test but works well under server like kestrel or IISExpress

project.json : 

    {
        "dependencies": {
            "EntityFramework.InMemory": "7.0.0-*",
            "xunit.runner.kre": "1.0.0-*"
        },
        "commands": {
            "test": "xunit.runner.kre"
        },
        "frameworks": {
            "aspnet50": { },
            "aspnetcore50": {
                "dependencies": {
                    "Microsoft.CSharp": "4.0.0-beta-*"
                }
            }
        }
    }

kvm output: 

    kvm list
    
    Active Version           Runtime Architecture Location                     Alias
    ------ -------           ------- ------------ --------                     -----
           1.0.0-beta3       clr     x64          C:\Users\Olivier\.k\runtimes
      *    1.0.0-beta3       clr     x86          C:\Users\Olivier\.k\runtimes default
           1.0.0-beta3       coreclr x64          C:\Users\Olivier\.k\runtimes
           1.0.0-beta3       coreclr x86          C:\Users\Olivier\.k\runtimes
           1.0.0-beta3-11030 clr     x86          C:\Users\Olivier\.k\runtimes
           1.0.0-beta3-11030 coreclr x86          C:\Users\Olivier\.k\runtimes

test code:

        [Fact]
        public void Connect()
        {
            var options = new ConfigurationOptions();
            options.EndPoints.Add("127.0.0.1:6375");
            ConnectionMultiplexer.Connect(options);
        }

tested code:

        /// <summary>
        /// Create a new ConnectionMultiplexer instance
        /// </summary>
        public static ConnectionMultiplexer Connect(ConfigurationOptions configuration, TextWriter log = null)
        {
            return ConnectImpl(() => CreateMultiplexer(configuration), log);
        }

        private static ConnectionMultiplexer ConnectImpl(Func<ConnectionMultiplexer> multiplexerFactory, TextWriter log)
        {
            IDisposable killMe = null;
            try
            {
                var muxer = multiplexerFactory();
                killMe = muxer;
                // note that task has timeouts internally, so it might take *just over* the regular timeout
                // wrap into task to force async execution
                var task = Task.Factory.StartNew(() => { return muxer.ReconfigureAsync(true, false, log, null, "connect").Result; });

                if (!task.Wait(muxer.SyncConnectTimeout(true)))
                {
                    task.ObserveErrors();
                    if (muxer.RawConfig.AbortOnConnectFail)
                    {
                        throw ExceptionFactory.UnableToConnect("Timeout");
                    }
                }
                if (!task.Result) throw ExceptionFactory.UnableToConnect(muxer.failureMessage);
                killMe = null;
                return muxer;
            }
            finally
            {
                if (killMe != null) try { killMe.Dispose(); } catch { }
            }
        }

the expression `() => { return muxer.ReconfigureAsync(true, false, log, null, "connect").Result; }` is never called and the exit because of timeout

    k test -method EntityFramework.Redis.Tests.RedisConnect.Connect
    xUnit.net K Runtime Environment test runner (32-bit Asp.Net 5.0)
    Copyright (C) 2014 Outercurve Foundation.
    
    Discovering: EntityFramework.Redis.Tests
    Discovered:  EntityFramework.Redis.Tests
    Starting:    EntityFramework.Redis.Tests
       EntityFramework.Redis.Tests.RedisConnect.Connect [FAIL]
          StackExchange.Redis.RedisConnectionException : It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. Timeout
          Stack Trace:
             C:\Users\Olivier\Source\Repos\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs(748,0): at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log)
             C:\Users\Olivier\Source\Repos\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs(729,0): at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log)
             RedisConnect.cs(14,0): at EntityFramework.Redis.Tests.RedisConnect.Connect()
    Finished:    EntityFramework.Redis.Tests
    
    === TEST EXECUTION SUMMARY ===
       EntityFramework.Redis.Tests  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 16.781s

The redis server is listening on port 6375 and works well:

    C:\Program Files\redis-2.8.17>redis-cli -p 6375
    127.0.0.1:6375> monitor
    OK

**Comment by bradwilson** [comment]
Please use `xunit.runner.aspnet`.

**Comment by aguacongas** [comment]
kpm restore is not abale to find some package if I use aspnet runner:

    kpm restore
    Restoring packages for C:\Users\Olivier\Source\Repos\EntityFramework\test\EntityFramework.Redis.Tests\project.json
      CACHE https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?Id='Microsoft.Framework.Logging'
      CACHE https://nuget.org/api/v2/FindPackagesById()?Id='Microsoft.Framework.Logging'
      CACHE https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?Id='Microsoft.Framework.OptionsModel'
      CACHE https://nuget.org/api/v2/FindPackagesById()?Id='Microsoft.Framework.OptionsModel'
      CACHE https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?Id='xunit.runner.aspnet'
      CACHE https://nuget.org/api/v2/FindPackagesById()?Id='xunit.runner.aspnet'
      CACHE https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?Id='Microsoft.Framework.TestAdapter'
      CACHE https://nuget.org/api/v2/FindPackagesById()?Id='Microsoft.Framework.TestAdapter'
      CACHE https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?Id='Microsoft.Framework.TestHost'
      CACHE https://nuget.org/api/v2/FindPackagesById()?Id='Microsoft.Framework.TestHost'
      CACHE https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?Id='Microsoft.Framework.Runtime.Interfaces'
      CACHE https://nuget.org/api/v2/FindPackagesById()?Id='Microsoft.Framework.Runtime.Interfaces'
    Resolving complete, 394ms elapsed
    Unable to locate Microsoft.Framework.TestAdapter >= 1.0.0-beta3-10745
    Unable to locate Microsoft.Framework.TestHost >= 1.0.0-beta3-10745
    Unable to locate Microsoft.Framework.Runtime.Interfaces >= 1.0.0-beta3-10914
    Restore complete, 416ms elapsed

**Comment by bradwilson** [comment]
Please follow these instructions:

http://xunit.github.io/docs/getting-started-aspnet.html

**Comment by aguacongas** [comment]
Thx a lot, it works
